version: "3.8"
services:
  backend:

    image: "wbenarto/springboot-react-fullstack:5.1.2023.23.47.15"

    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev